name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install xmake
      run: bash <(curl -fsSL https://xmake.io/shget.text)
    - name: xmake
      run: make
    - name: test
      run: xmake r -w `pwd` lexical-analyzer -s ./test/test0.c 
